# Generated by Django 4.2.7 on 2023-11-30 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id_breed', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id_person', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('patronymic', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Dogs',
            fields=[
                ('id_dog', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('mark', models.CharField(max_length=100)),
                ('chip', models.CharField(max_length=100)),
                ('birthdate', models.CharField(max_length=100)),
                ('deathdate', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('kennel', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=100)),
                ('id_breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.breed')),
                ('id_breeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeder', to='main_page.person')),
                ('id_dad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daddog', to='main_page.dogs')),
                ('id_mom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='momdog', to='main_page.dogs')),
                ('id_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='main_page.person')),
            ],
        ),
    ]
