# Generated by Django 4.2.7 on 2023-12-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
