# Generated by Django 4.2.7 on 2023-12-18 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_user_alter_breed_image_alter_dogs_id_breeder_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
